variable "ec2_count" {}
variable "ami_id" {}
variable "instance_type" {}
variable "key_name" {}
variable "instance_name" {}
#variable "user_data" {}
variable "aws_region" {}
variable "subnet_id" {}
variable "environment_tag" {}
variable "role_name" {}
variable "instance_profile" {}
variable "role_policy" {}
variable "security_group_name" {}
variable "owner" {}
variable "project" {}